# 一、ndarray
## 1.ndarray特性

多维性

In [ ]:
import numpy as np

print("numpy 版本：", np.__version__)

In [2]:
arr = np.array(5)
print(arr)
print('arr的维度:', arr.ndim)

5
arr的维度: 0


In [3]:
arr = np.array([1, 2, 3])
print(arr)
print('arr的维度:', arr.ndim)

[1 2 3]
arr的维度: 1


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('arr的维度:', arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度: 2


同质性

In [5]:
arr = np.array([1, 'hello'])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

['1' 'hello']


In [6]:
arr = np.array([1, 2.5])
print(arr)

[1.  2.5]


## 2.ndrray的属性

In [7]:
arr = np.array(1)
print(arr)
print('数组的形状:', arr.shape)
print('数组的维度:', arr.ndim)
print('数组的个数:', arr.size)
print('数组的数据类型:', arr.dtype)
print('数组的转置:', arr.T)
print('数组的单个元素占用的内存字节数:', arr.itemsize)
print('数组的总内存占用量:', arr.nbytes)
print('数组的内存存储方式(是否连续存储):', arr.flags)

1
数组的形状: ()
数组的维度: 0
数组的个数: 1
数组的数据类型: int64
数组的转置: 1
数组的单个元素占用的内存字节数: 8
数组的总内存占用量: 8
数组的内存存储方式(是否连续存储):   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [8]:
arr = np.array([1, 2.5, 3])
print(arr)
print('数组的形状:', arr.shape)
print('数组的维度:', arr.ndim)
print('数组的个数:', arr.size)
print('数组的数据类型:', arr.dtype)
print('数组的转置:', arr.T)
print('数组的单个元素占用的内存字节数:', arr.itemsize)
print('数组的总内存占用量:', arr.nbytes)
print('数组的内存存储方式(是否连续存储):', arr.flags)

[1.  2.5 3. ]
数组的形状: (3,)
数组的维度: 1
数组的个数: 3
数组的数据类型: float64
数组的转置: [1.  2.5 3. ]
数组的单个元素占用的内存字节数: 8
数组的总内存占用量: 24
数组的内存存储方式(是否连续存储):   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状:', arr.shape)
print('数组的维度:', arr.ndim)
print('数组的个数:', arr.size)
print('数组的数据类型:', arr.dtype)
print('数组的转置:', arr.T)
print('数组的单个元素占用的内存字节数:', arr.itemsize)
print('数组的总内存占用量:', arr.nbytes)
print('数组的内存存储方式(是否连续存储):', arr.flags)

[[1 2 3]
 [4 5 6]]
数组的形状: (2, 3)
数组的维度: 2
数组的个数: 6
数组的数据类型: int64
数组的转置: [[1 4]
 [2 5]
 [3 6]]
数组的单个元素占用的内存字节数: 8
数组的总内存占用量: 48
数组的内存存储方式(是否连续存储):   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## 3.ndaray的创建

In [10]:
# 基础的创建方法
list1 = [4, 5, 6]
arr = np.array(list1, dtype=np.float64)
print(arr.ndim)
print(arr)

1
[4. 5. 6.]


In [11]:
# copy
arr1 = np.copy(arr)  # 元素跟原始的数组相同，但是不是一个数组了
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]


In [12]:
# 预定义形状
# 全0  全1  未初始化  固定值
arr = np.zeros((2, 3), dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [13]:
arr = np.zeros((200,), dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [14]:
arr = np.ones((5, 8), dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [28]:
arr = np.empty((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [33]:
arr = np.empty((4, 2))
print(arr)

[[3.7104e-321 1.7673e-320]
 [6.5365e-321 1.4768e-320]
 [1.4768e-320 6.5365e-321]
 [1.7673e-320 3.7104e-321]]


In [34]:
arr = np.full((3, 4), 2026)
print(arr)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [38]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr, 2027)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2027 2027 2027 2027]
 [2027 2027 2027 2027]
 [2027 2027 2027 2027]]


In [39]:
# 等差数列
arr = np.arange(1, 51, 20)  # start,end,step(步长）
print(arr)

[ 1 21 41]


In [40]:
# 等间隔数列
# 生成指定数量的等间隔值（含终点）
arr = np.linspace(0, 100, 5)
print(arr)

[  0.  25.  50.  75. 100.]


In [42]:
arr = np.linspace(0, 500, 5, dtype=int)
print(arr)
arr = np.arange(0, 501, 125)
print(arr)

[  0 125 250 375 500]
[  0 125 250 375 500]


In [43]:
# 对数间隔数列
arr = np.logspace(0, 4, 3, base=2)
print(arr)

[ 1.  4. 16.]


In [45]:
arr = np.linspace(0, 4, 3)
print(arr)

[0. 2. 4.]


In [44]:
arr = np.logspace(0, 4, 3)
print(arr)

[1.e+00 1.e+02 1.e+04]


In [46]:
# 特殊矩阵
# 单位矩阵：主对角线上的数字为1，其他的数字为0
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [47]:
# 对角矩阵：主对角线上非零的0，其他的数字为0
arr = np.diag([5, 1, 23, 25])
print(arr)

[[ 5  0  0  0]
 [ 0  1  0  0]
 [ 0  0 23  0]
 [ 0  0  0 25]]


In [48]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(3, 4)
print(arr)

[[0.11039481 0.56805599 0.96684209 0.55023854]
 [0.99405702 0.82789095 0.46730863 0.71240606]
 [0.57681333 0.35025499 0.20496947 0.14000583]]


In [49]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(10, 50, (2, 5))
print(arr)

[[22.92595616 30.78441961 43.14889686 20.10181249 40.06302669]
 [18.49676239 12.44029122 24.57468583 32.52577945 45.65357926]]


In [51]:
# 生成指定范围区间的随机整数
arr = np.random.randint(4, 80, (2, 3))
print(arr)

[[20 41 56]
 [77 35 70]]


In [52]:
# 生成随机数列（正态分布）（-3到3之间）
# 两边小，中间大
#
arr = np.random.randn(4, 2)
print(arr)

[[ 2.11373848  0.61379296]
 [ 0.8931379   0.04663077]
 [-0.35452162  0.43039609]
 [ 0.74848273  0.52570266]]


In [53]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1, 10, (5, 2))
print(arr)

[[4 5]
 [7 8]
 [3 1]
 [7 9]
 [6 4]]


In [54]:
arr = np.array([1, 2, 3], dtype='i8')  # int，8个字节
print(arr)

[1 2 3]


## 4.ndarray的数据类型

布尔类型 bool

整数类型 int uint

浮点数 float

复数 complex

In [55]:
arr = np.array([1, 0, 127, 0], dtype=np.int8)
print(arr)

[  1   0 127   0]


## 5.索引与切片

In [56]:
# 一维数组的索引与切片
arr = np.random.randint(1, 100, 20)
print(arr)

[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]


In [57]:
print(arr[10])
print(arr[:])
print(arr[2:5])  # start:end+1 左包右不包
print(arr[slice(2, 15, 3)])  #start,end,step
print(arr[(arr > 10) & (arr < 70)])

26
[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]
[17  8 99]
[17  7 76  4 62]
[17 63 17 27 14 59 26 62 58 33]


In [59]:
# 二维数组的索引与切片
arr = np.random.randint(1, 100, (4, 8))
print(arr)

[[11  7 76 19  4 78 18 44]
 [17 19 80 91 60 72 76 30]
 [46  7 64 79 25 19 94 34]
 [79 43 95  4 19 71 53 23]]


In [60]:
print(arr[1, 3])
print(arr[1, 2:5])
print(arr[2][arr[2] > 50])
print(arr[:, 3])

91
[80 91 60]
[64 79 94]
[19 91 79  4]


## 5.ndarray的运算

In [61]:
# 算术运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [62]:
c = [1, 2, 3]
d = [4, 5, 6]
for i in range(len(c)):
    d[i] = d[i] + c[i]
print(d)

[5, 7, 9]


In [67]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]
 [1 2 3]]
[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [68]:
# 数组与标量之间的算术运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a + 3)
print(a * 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [69]:
# 广播机制: 1.获取形状 2.是否可广播
# 同一维度：相同、1
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
print(b - a)

[[3 2 1]
 [4 3 2]
 [5 4 3]]


In [71]:
# 无法进行广播机制
# a = np.array([1,2,3]) #1*3
# b = np.array([4,5])  #1*2
# print(b - a )

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [72]:
# 矩阵运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a @ b)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


## 2.3 numpy中的常用函数

## 1.基本数学函数

In [74]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [75]:
# 计算指数  e^x  = y,计算e的x次方是多少
print(np.exp(1))

2.718281828459045


In [76]:
# 计算自然对数  ln y = x
print(np.log(2.71))

0.9969486348916096


In [77]:
# 计算正弦值、余弦值
print(np.sin(np.pi / 2))
print(np.cos(np.pi))

1.0
-1.0


In [78]:
# 计算绝对值
arr = np.array([-1, 1, 2, -3])
print(np.abs(arr))

[1 1 2 3]


In [79]:
# 计算a的b次幂
print(np.power(arr, 3))

[ -1   1   8 -27]


In [80]:
# 四舍五入
print(np.round([3.2, 4.5, 8.1, 9.6]))

[ 3.  4.  8. 10.]


In [81]:
# 向上取整，向下取整
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [82]:
# 检测缺失值NaN
np.isnan([1, 2, np.nan, 23])

array([False, False,  True, False])

##2.统计函数

求和、计算平均值、计算中位数、标准差、方差

查找最大值、最小值

计算分位数、累积和、累积差


In [83]:
arr = np.random.randint(1, 200, 8)
print(arr)

[143   5  28  76   9   7  27  83]


In [84]:
# 求和
print(np.sum([1, 2, 3]))

6


In [85]:
# 计算平均值
print(np.mean(arr))

47.25


In [86]:
# 计算中位数
# 奇数：排序后中间的数值
# 偶数：中间的两个数的平均值
print(np.median([4, 1, 2]))
print(np.median([1, 1, 1, 1, 1, 1, 1, 1, 1, 100]))

2.0
1.0


In [88]:
# 计算标准差、方差
arr1 = np.array([1, 2, 1, 2, 1, 1, 1, 2])
arr2 = np.array([1, 0, 3, 0, 0, 0, 4, 3])
print(np.mean(arr1))
print(np.mean(arr2))
print(np.var(arr1))
print(np.var(arr2))
print(np.std(arr1))
print(np.std(arr2))

1.375
1.375
0.234375
2.484375
0.4841229182759271
1.5761900266148114


In [89]:
# 计算最大值、最小值
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

[143   5  28  76   9   7  27  83]
143 0
5 1


In [91]:
# 分位数
print(np.median([1, 2, 3]))
print([1, 2, 3, 4])
np.random.randint(0, 100, 4)
print(arr)
print(np.median(arr))
print(np.percentile(arr, 80))

2.0
[1, 2, 3, 4]
[143   5  28  76   9   7  27  83]
27.5
80.2


In [92]:
# 累积和、累积积
arr = np.array([1, 2, 3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

6
[1 3 6]
[1 2 6]


In [94]:
# 创建嵌套JSON结构的数据
import numpy as np

products = {
    "products": [
        {
            "id": f"P{i}",
            "name": f"Product {i}",
            "category": np.random.choice(["Electronics", "Clothing", "Home", "Food"]),
            "price": round(np.random.uniform(5, 200), 2),
            "in_stock": bool(np.random.choice([True, False])),
            "specs": {
                "weight": round(np.random.uniform(0.1, 5), 2),
                "dimensions": {
                    "length": np.random.randint(5, 50),
                    "width": np.random.randint(5, 30),
                    "height": np.random.randint(5, 20)
                }
            }
        } for i in range(1, 21)
    ]
}

# 保存为JSON
import json

with open('data/products.json', 'w') as f:
    json.dump(products, f, indent=2)